"""empty message

Revision ID: 37ce31d36f10
Revises: 
Create Date: 2023-06-07 21:00:00.541878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ce31d36f10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('is_blocked', sa.BOOLEAN(), nullable=True),
    sa.Column('balance', sa.SMALLINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_reservation',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('date_reservation', sa.TIMESTAMP(), nullable=False),
    sa.Column('number_of_quests', sa.SMALLINT(), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_reservation')
    op.drop_table('user')
    # ### end Alembic commands ###
